// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJiTEtc0jk8TbgvuWsatqm_whjUbX5ZUY',
    appId: '1:17264006648:web:f7e8b98234ce98e7bfb20d',
    messagingSenderId: '17264006648',
    projectId: 'e-tourism-6a96b',
    authDomain: 'e-tourism-6a96b.firebaseapp.com',
    storageBucket: 'e-tourism-6a96b.appspot.com',
    measurementId: 'G-TTL7KVZ7X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTD48z1U4i7PA2dUBvhyEoZYsSuix-MuY',
    appId: '1:17264006648:android:142f01e9bdf44dc8bfb20d',
    messagingSenderId: '17264006648',
    projectId: 'e-tourism-6a96b',
    storageBucket: 'e-tourism-6a96b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8F1xgx6n3vg2Yuwoc_tdmokf7C5EyUn0',
    appId: '1:17264006648:ios:76255033a87fd383bfb20d',
    messagingSenderId: '17264006648',
    projectId: 'e-tourism-6a96b',
    storageBucket: 'e-tourism-6a96b.appspot.com',
    iosBundleId: 'com.example.eTourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8F1xgx6n3vg2Yuwoc_tdmokf7C5EyUn0',
    appId: '1:17264006648:ios:76255033a87fd383bfb20d',
    messagingSenderId: '17264006648',
    projectId: 'e-tourism-6a96b',
    storageBucket: 'e-tourism-6a96b.appspot.com',
    iosBundleId: 'com.example.eTourism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJiTEtc0jk8TbgvuWsatqm_whjUbX5ZUY',
    appId: '1:17264006648:web:3819a309ab20a3a6bfb20d',
    messagingSenderId: '17264006648',
    projectId: 'e-tourism-6a96b',
    authDomain: 'e-tourism-6a96b.firebaseapp.com',
    storageBucket: 'e-tourism-6a96b.appspot.com',
    measurementId: 'G-1F9SPEK4GJ',
  );

}